spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/productdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    enabled: true

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Logging Configuration (Optional)
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

